name: Build Kafka API Docker Image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  dockerbuild:
    runs-on: ubuntu-latest
    
    # Make outputs SHORT_SHA available to next bump job
    outputs:
      short_sha: ${{ steps.getbuildversion.outputs.buildversion }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean package --file kafka/pom.xml

    - name: List Built Generated Components
      run: |-
        pwd && ls -lrt && ls -lrt kafka/target

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Create image tag
    - name: Add SHORT_SHA env property with HEAD
      id: getbuildversion
      run: echo "::set-output name=buildversion::$(echo api-${GITHUB_SHA::4})"
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: ./kafka
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/kafka-api:${{ steps.getbuildversion.outputs.buildversion }}
        cache-from: ${{ secrets.DOCKERHUB_USERNAME }}/kafka
        cache-to: ${{ secrets.DOCKERHUB_USERNAME }}/kafka

