name: Build Kafka API Docker Image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  dockerbuild:
    runs-on: ubuntu-latest
    
    # Make outputs SHORT_SHA available to next bump job
    outputs:
      short_sha: ${{ steps.getbuildversion.outputs.buildversion }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean package --file kafka/pom.xml

    - name: List Built Generated Components
      run: |-
        pwd && ls -lrt && ls -lrt kafka
